<Project Sdk="Microsoft.NET.Sdk">

    <!-- ==================== CORE VARIABLES ==================== -->
    <PropertyGroup>
        <Project_Name>Bluetooth.Maui</Project_Name>
        <Project_Tags>Bluetooth;Maui;Android;iOS;MacCatalyst;Windows;Tools;Toolkit</Project_Tags>
        <Project_Copyright>Francois Raminosona</Project_Copyright>
        <Project_Description>Bluetooth.Maui for .NET Maui</Project_Description>
    </PropertyGroup>

    <!-- ==================== NOWARNINGS ==================== -->
    <PropertyGroup>
        <!-- CA1034 : Nested types should not be externally visible-->
        <NoWarn>$(NoWarn);CA1034</NoWarn>
        <!-- CA1032 : Implement standard exception constructors -->
        <NoWarn>$(NoWarn);CA1032</NoWarn>
        <!-- CS1591 : Missing documentation for publicly visible type or member -->
        <!-- <NoWarn>$(NoWarn);CS1591</NoWarn> -->
        <!-- CA1816 : Call GC.SuppressFinalize correctly -->
        <NoWarn>$(NoWarn);CA1816</NoWarn>
    </PropertyGroup>

    <!-- ==================== TARGET FRAMEWORKS ==================== -->
    <PropertyGroup>
        <TargetFrameworks>net10.0;net10.0-android</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);net10.0-maccatalyst</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);net10.0-ios</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);net10.0-windows10.0.22621.0</TargetFrameworks>
    </PropertyGroup>

    <!-- ==================== MAUI ==================== -->
    <PropertyGroup>
        <UseMaui>true</UseMaui>
        <SingleProject>true</SingleProject>
    </PropertyGroup>

    <!-- ==================== PACKAGE REFERENCES / DEPENDENCIES ==================== -->
    <ItemGroup>
        <ProjectReference Include="../Bluetooth.Abstractions/Bluetooth.Abstractions.csproj" PrivateAssets="all" />
        <ProjectReference Include="../Bluetooth.Abstractions.Scanning/Bluetooth.Abstractions.Scanning.csproj" PrivateAssets="all" />
        <ProjectReference Include="../Bluetooth.Abstractions.Broadcasting/Bluetooth.Abstractions.Broadcasting.csproj" PrivateAssets="all" />

        <ProjectReference Include="../Bluetooth.Core/Bluetooth.Core.csproj" PrivateAssets="all" />
        <ProjectReference Include="../Bluetooth.Core.Broadcasting/Bluetooth.Core.Broadcasting.csproj" PrivateAssets="all" />
        <ProjectReference Include="../Bluetooth.Core.Scanning/Bluetooth.Core.Scanning.csproj" PrivateAssets="all" />

        <ProjectReference Condition=" '$(IsForAndroid)' == 'true' " Include="../Bluetooth.Maui.Platforms.Droid/Bluetooth.Maui.Platforms.Droid.csproj" PrivateAssets="all" />
        <ProjectReference Condition=" '$(IsForAppleStuff)' == 'true' " Include="../Bluetooth.Maui.Platforms.Apple/Bluetooth.Maui.Platforms.Apple.csproj" PrivateAssets="all" />
        <ProjectReference Condition=" '$(IsForWindows)' == 'true' " Include="../Bluetooth.Maui.Platforms.Win/Bluetooth.Maui.Platforms.Win.csproj" PrivateAssets="all" />
        <ProjectReference Condition=" '$(IsForPlainNetX)' == 'true' " Include="../Bluetooth.Maui.Platforms.DotNetCore/Bluetooth.Maui.Platforms.DotNetCore.csproj" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Maui" />
        <PackageReference Include="CommunityToolkit.Maui.Markup" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" />
        <PackageReference Include="Plugin.ByteArrays" />
        <PackageReference Include="Plugin.BaseTypeExtensions" />
        <PackageReference Include="Plugin.ExceptionListeners" />
        <PackageReference Include="Plugin.ExceptionListeners.Maui" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Builders\" />
    </ItemGroup>
</Project>
