<Project Sdk="Microsoft.NET.Sdk">

    <!-- ==================== CORE VARIABLES ==================== -->
    <PropertyGroup>
        <Project_Name>Bluetooth.Maui.Platforms.Apple</Project_Name>
        <Project_Tags>Bluetooth;Maui;iOS;MacCatalyst;Tools;Toolkit</Project_Tags>
        <Project_Copyright>Francois Raminosona</Project_Copyright>
        <Project_Description>Apple platform implementation for Bluetooth.Maui</Project_Description>
    </PropertyGroup>

    <!-- ==================== NOWARNINGS ==================== -->
    <PropertyGroup>
        <!-- CA1034 : Nested types should not be externally visible-->
        <NoWarn>$(NoWarn);CA1034</NoWarn>
        <!-- CA1032 : Implement standard exception constructors -->
        <NoWarn>$(NoWarn);CA1032</NoWarn>
        <!-- CS1591 : Missing documentation for publicly visible type or member -->
        <!-- <NoWarn>$(NoWarn);CS1591</NoWarn> -->
        <!-- CA1816 : Call GC.SuppressFinalize correctly -->
        <NoWarn>$(NoWarn);CA1816</NoWarn>
    </PropertyGroup>

    <!-- ==================== TARGET FRAMEWORKS ==================== -->
    <PropertyGroup>
        <TargetFrameworks>$(TargetFrameworks);net10.0-maccatalyst</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);net10.0-ios</TargetFrameworks>
    </PropertyGroup>

    <!-- ==================== PACKAGING ==================== -->
    <PropertyGroup>
        <!-- Only package in Debug mode for local testing - Release builds only package Bluetooth.Maui -->
        <IsPackable Condition="'$(Configuration)' == 'Release'">false</IsPackable>
    </PropertyGroup>

    <!-- ==================== PACKAGE REFERENCES / DEPENDENCIES ==================== -->
    <ItemGroup>
        <ProjectReference Include="../Bluetooth.Abstractions/Bluetooth.Abstractions.csproj" PrivateAssets="all" />
        <ProjectReference Include="../Bluetooth.Abstractions.Scanning/Bluetooth.Abstractions.Scanning.csproj" PrivateAssets="all" />
        <ProjectReference Include="../Bluetooth.Abstractions.Broadcasting/Bluetooth.Abstractions.Broadcasting.csproj" PrivateAssets="all" />

        <ProjectReference Include="../Bluetooth.Core/Bluetooth.Core.csproj" PrivateAssets="all" />
        <ProjectReference Include="../Bluetooth.Core.Broadcasting/Bluetooth.Core.Broadcasting.csproj" PrivateAssets="all" />
        <ProjectReference Include="../Bluetooth.Core.Scanning/Bluetooth.Core.Scanning.csproj" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Maui" />
        <PackageReference Include="CommunityToolkit.Maui.Markup" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" />
        <PackageReference Include="Plugin.ByteArrays" />
        <PackageReference Include="Plugin.BaseTypeExtensions" />
        <PackageReference Include="Plugin.ExceptionListeners" />
        <PackageReference Include="Plugin.ExceptionListeners.Maui" />
    </ItemGroup>
</Project>
