<Project Sdk="Microsoft.NET.Sdk">

    <!-- ==================== CORE VARIABLES ==================== -->
    <PropertyGroup>
        <Project_Name>Bluetooth.Core</Project_Name>
        <Project_Tags>Bluetooth;Core;Tools;Toolkit</Project_Tags>
        <Project_Copyright>Francois Raminosona</Project_Copyright>
        <Project_Description>Bluetooth.Core for .NET</Project_Description>
    </PropertyGroup>

    <!-- ==================== NOWARNINGS ==================== -->
    <PropertyGroup>
        <!-- CA1034 : Nested types should not be externally visible-->
        <NoWarn>$(NoWarn);CA1034</NoWarn>
        <!-- CA1032 : Implement standard exception constructors -->
        <NoWarn>$(NoWarn);CA1032</NoWarn>
        <!-- CS1591 : Missing documentation for publicly visible type or member -->
        <!-- <NoWarn>$(NoWarn);CS1591</NoWarn> -->
        <!-- CA1816 : Call GC.SuppressFinalize correctly -->
        <NoWarn>$(NoWarn);CA1816</NoWarn>
    </PropertyGroup>

    <!-- ==================== TARGET FRAMEWORKS ==================== -->
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <!-- ==================== PACKAGING ==================== -->
    <PropertyGroup>
        <!-- Only package in Debug mode for local testing - Release builds only package Bluetooth.Maui -->
        <IsPackable Condition="'$(Configuration)' == 'Release'">false</IsPackable>
    </PropertyGroup>

    <!-- ==================== PACKAGE REFERENCES / DEPENDENCIES ==================== -->
    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Maui" />
        <PackageReference Include="CommunityToolkit.Maui.Markup" />
        <PackageReference Include="CommunityToolkit.Mvvm" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" />
        <PackageReference Include="Plugin.ByteArrays" />
        <PackageReference Include="Plugin.BaseTypeExtensions" />
        <PackageReference Include="Plugin.ExceptionListeners" />
    </ItemGroup>

    <!-- ==================== PROJECT REFERENCES / DEPENDENCIES ==================== -->
    <ItemGroup>
      <ProjectReference Include="..\Bluetooth.Abstractions\Bluetooth.Abstractions.csproj" PrivateAssets="all" />
    </ItemGroup>
</Project>
